# Generated by Django 6.0.5 on 2026-05-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=10000.0)),
                ('equity', models.FloatField(default=10000.0)),
                ('margin_used', models.FloatField(default=0.0)),
            ],
        ),
    ]
